from enum import Enum


class RangeStatus(str, Enum):
    WITHIN_SOURCE_RANGE = "WITHIN_SOURCE_RANGE"
    BELOW_SOURCE_RANGE = "BELOW_SOURCE_RANGE"
    ABOVE_SOURCE_RANGE = "ABOVE_SOURCE_RANGE"
    NOT_DETERMINED = "NOT_DETERMINED"


class Origin(str, Enum):
    USER_PROVIDED = "USER_PROVIDED"
    SYNTHETIC_SOURCE = "SYNTHETIC_SOURCE"
    AI_EXTRACTED = "AI_EXTRACTED"
    HUMAN_VERIFIED = "HUMAN_VERIFIED"


class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    EDITED = "EDITED"
    VERIFIED = "VERIFIED"
    FLAGGED = "FLAGGED"
