import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, ArrowRight, Check, Flag, LoaderCircle } from "lucide-react";
import { apiClient } from "../lib/api";
import type { Conflict, ConflictSide } from "../types/api";

function Side({ label, side }: { label: string; side?: ConflictSide | null }) {
  if (!side) return <section className="panel"><p className="eyebrow">{label}</p><p>Source unavailable.</p></section>;
  return <section className="panel conflict-side"><p className="eyebrow">{label}</p><h3>{side.value ?? "Documented entry"}</h3><p>{side.source_document ?? "Source document unavailable"}{side.source_page ? ` · page ${side.source_page}` : ""}</p><blockquote>{side.source_text ?? "No source text was preserved."}</blockquote><p className="muted">Verification: {side.verification?.status ?? "PENDING"}</p>{side.report_id ? <Link className="text-link" to={`/reports/${side.report_id}/review`}>Open report <ArrowRight size={14} /></Link> : null}</section>;
}

export function ConflictCenterPage() {
  const [conflicts, setConflicts] = useState<Conflict[]>([]); const [selected, setSelected] = useState<Conflict | null>(null); const [decision, setDecision] = useState<"SOURCE_A" | "SOURCE_B" | "UNRESOLVED">("UNRESOLVED"); const [notes, setNotes] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = () => { setLoading(true); setError(""); apiClient.getConflicts().then(setConflicts).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const act = async (kind: "resolve" | "flag") => { if (!selected) return; setSaving(true); setError(""); try { const next = kind === "resolve" ? await apiClient.resolveConflict(selected.id, decision, notes) : await apiClient.flagConflict(selected.id, notes); setConflicts((items) => items.map((item) => item.id === next.id ? next : item)); setSelected(next); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } };
  return <main className="page-stack"><header className="page-heading"><div><p className="eyebrow">Human review</p><h1>Conflict Center</h1><p>Conflicting source facts stay visible until a person decides how to handle them.</p></div><div className="trust-note"><AlertTriangle size={18} /> Never silently choose a medical value</div></header>{error && <div className="error-banner" role="alert">{error}</div>}{loading ? <div className="state-card"><LoaderCircle className="spin" /> Loading conflicts...</div> : conflicts.length === 0 ? <div className="state-card"><Check size={24} /><h2>No conflicts detected</h2><p>When deterministic checks find conflicting documented facts, they will appear here.</p></div> : <div className="conflict-layout"><div className="conflict-list">{conflicts.map((item) => <button className={`conflict-card ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => { setSelected(item); setDecision(item.status === "RESOLVED" ? "SOURCE_A" : "UNRESOLVED"); setNotes(""); }}><span className="status-pill">{item.status}</span><strong>{item.conflict_type.replaceAll("_", " ")}</strong><span>{item.description}</span><small>{item.severity} severity</small></button>)}</div>{selected && <div className="conflict-detail"><div className="detail-heading"><div><p className="eyebrow">Conflict #{selected.id}</p><h2>Review both sources</h2><p>{selected.description}</p></div><span className="status-pill">{selected.status}</span></div><div className="conflict-sides"><Side label="Source A" side={selected.source_a} /><Side label="Source B" side={selected.source_b} /></div><div className="panel decision-panel"><p className="eyebrow">Human decision</p><label><input type="radio" checked={decision === "SOURCE_A"} onChange={() => setDecision("SOURCE_A")} /> Keep Source A</label><label><input type="radio" checked={decision === "SOURCE_B"} onChange={() => setDecision("SOURCE_B")} /> Keep Source B</label><label><input type="radio" checked={decision === "UNRESOLVED"} onChange={() => setDecision("UNRESOLVED")} /> Leave unresolved</label><label className="field-label">Notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Explain the review decision" /></label><div className="button-row"><button className="primary-button" disabled={saving} onClick={() => act("resolve")}>{saving ? "Saving..." : "Record decision"}</button><button className="secondary-button" disabled={saving} onClick={() => act("flag")}><Flag size={16} /> Flag for follow-up</button></div></div></div>}</div>}</main>;
}
