import { useEffect, useState } from "react";
import { AlertCircle, ArrowDown, ArrowUp, Check, CircleHelp, FileText, RefreshCw, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { SourceReference } from "../components/ui/SourceReference";
import { StatusBadge, type StatusKind } from "../components/ui/StatusBadge";
import { TrustChain } from "../components/ui/TrustChain";
import { VerificationBadge } from "../components/ui/VerificationBadge";
import { apiClient } from "../lib/api";
import type { ExtractedFact, ReviewResponse } from "../types/api";

const statusKind = (value?: string): StatusKind => value === "BELOW_SOURCE_RANGE" ? "below" : value === "ABOVE_SOURCE_RANGE" ? "above" : value === "WITHIN_SOURCE_RANGE" ? "within" : "undetermined";
const displayName = (fact: ExtractedFact) => fact.test_name ?? fact.name ?? "Documented item";
export function ExtractionReviewPage() { const { reportId } = useParams(); const [review, setReview] = useState<ReviewResponse>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const load = () => { setLoading(true); setError(""); apiClient.getReview(Number(reportId)).then(setReview).catch(error => setError(error instanceof Error ? error.message : "Review data could not be loaded.")).finally(() => setLoading(false)); }; useEffect(load, [reportId]); if (loading) return <div className="page review-page"><PageHeader eyebrow="Extraction review" title="Loading review" description="Retrieving the persisted structured record and its source links." /><div className="review-loading" role="status"><RefreshCw className="spin" size={18} /> Loading documented facts…</div></div>; if (error || !review) return <div className="page review-page"><PageHeader eyebrow="Extraction review" title="Review unavailable" description="The extraction review could not be loaded." /><div className="submit-error" role="alert"><AlertCircle size={17} />{error}</div><button className="secondary-action retry-action" onClick={load}><RefreshCw size={14} /> Retry</button></div>; const facts = [...review.lab_results, ...review.medications, ...review.allergies, ...review.conditions]; return <div className="page review-page"><PageHeader eyebrow="Extraction review" title="Extraction Review" description="Review documented facts before any human verification. AI extraction is not medical diagnosis." /><div className="review-report"><FileText size={16} /><span><b>{review.report.filename}</b><small>Report #{review.report.id} · {review.report.pages} pages · {facts.length} facts extracted</small></span></div><TrustChain active={review.verification.length ? 3 : 2} />{review.conflicts.length > 0 && <div className="conflict-banner" role="alert"><AlertCircle size={17} /><span><b>Conflict detected</b><small>{review.conflicts.length} conflict(s) require human review. No value was selected automatically.</small></span></div>}<section className="facts-section"><div className="section-heading"><div><div className="eyebrow">Structured record</div><h2>Documented facts</h2></div><span className="status-badge status-muted">{facts.length} pending review</span></div>{facts.length === 0 ? <div className="empty-state compact" role="status"><CircleHelp size={22} /><p>No explicit facts were extracted from this document.</p></div> : <div className="fact-list">{facts.map(fact => <FactRow key={`${fact.id}-${displayName(fact)}`} fact={fact} document={review.report.filename} />)}</div>}</section><Link className="back-link" to={`/patients/${review.report.patient_id}/reports/new`}>Upload another report</Link></div>; }
function FactRow({ fact, document }: { fact: ExtractedFact; document: string }) { return <article className="fact-row"><div className="fact-main"><div className="fact-name"><span className="fact-type">{fact.test_name ? "Lab result" : "Documented"}</span><h3>{displayName(fact)}</h3></div>{fact.value !== undefined && <div className="fact-value"><strong>{fact.value ?? "Not reported"}</strong>{fact.unit && <span>{fact.unit}</span>}</div>}{fact.reference_text && <p className="reference-copy">Reference range: {fact.reference_text}</p>}{fact.range_status && <StatusBadge kind={statusKind(fact.range_status)} />}</div><div className="fact-meta"><SourceReference document={document} page={fact.source_page ?? undefined} /><VerificationBadge state="pending" /><span className="origin-label"><ShieldCheck size={14} /> AI extracted</span><details><summary>View source text</summary><p>{fact.source_text ?? "Source text was not returned."}</p></details></div></article>; }
