import { useRef, useState } from "react";
import type { DragEvent } from "react";
import { AlertCircle, ArrowRight, CheckCircle2, FileUp, LoaderCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { PageHeader } from "../components/PageHeader";
import { apiClient } from "../lib/api";
import type { ReportUpload } from "../types/api";

type UploadState = "empty" | "drag-over" | "validating" | "uploading" | "processing" | "ready" | "invalid" | "failed";
const MAX_FILE_SIZE = 10 * 1024 * 1024;
const errorFor = (file: File) => file.size === 0 ? "This file is empty." : file.size > MAX_FILE_SIZE ? "File is too large. Choose a PDF under 10 MB." : file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf") ? "Unsupported file type. Choose a PDF." : undefined;

export function ReportUploadPage() {
  const { patientId } = useParams(); const navigate = useNavigate(); const inputRef = useRef<HTMLInputElement>(null); const [state, setState] = useState<UploadState>("empty"); const [file, setFile] = useState<File>(); const [report, setReport] = useState<ReportUpload>(); const [error, setError] = useState(""); const numericPatientId = Number(patientId);
  const chooseFile = async (candidate?: File) => { if (!candidate) return; const validationError = errorFor(candidate); setFile(candidate); setError(validationError ?? ""); if (validationError) { setState("invalid"); return; } setState("validating"); await new Promise(resolve => setTimeout(resolve, 180)); setState("uploading"); try { const created = await apiClient.uploadReport(numericPatientId, candidate); setReport(created); setState("processing"); await apiClient.extractReport(created.id); setState("ready"); } catch (uploadError) { setState("failed"); setError(uploadError instanceof Error ? uploadError.message : "That file could not be processed. Please choose another PDF."); } };
  const browse = () => inputRef.current?.click();
  const reset = () => { setFile(undefined); setReport(undefined); setError(""); setState("empty"); if (inputRef.current) inputRef.current.value = ""; };
  const onDrop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setState("empty"); void chooseFile(event.dataTransfer.files[0]); };
  const busy = state === "validating" || state === "uploading" || state === "processing";
  return <div className="page upload-page"><PageHeader eyebrow="Synthetic Patient 01 · Report intake" title="Upload Medical Report" description="Add a medical report to organize its documented information into a structured, reviewable record." /><div className="upload-context"><span className="patient-context-icon"><ShieldCheck size={17} /></span><span><b>Synthetic Patient 01</b><small>DEMO ENVIRONMENT · SYNTHETIC DATA ONLY</small></span></div><input ref={inputRef} className="visually-hidden" type="file" accept="application/pdf,.pdf" onChange={event => void chooseFile(event.target.files?.[0])} aria-label="Choose a PDF medical report" />{state === "ready" && report ? <ReadyState report={report} file={file!} onAnother={reset} onReview={() => navigate(`/reports/${report.id}/review`)} /> : <><div className={`upload-zone ${state === "drag-over" ? "drag-active" : ""} ${busy ? "is-busy" : ""}`} onDragEnter={event => { event.preventDefault(); if (!busy) setState("drag-over"); }} onDragOver={event => event.preventDefault()} onDragLeave={() => state === "drag-over" && setState("empty")} onDrop={onDrop} role="group" aria-label="PDF report upload area"><span className="upload-mark">{busy ? <LoaderCircle className="spin" size={27} /> : state === "invalid" || state === "failed" ? <AlertCircle size={27} /> : <FileUp size={27} />}</span><h2>{state === "drag-over" ? "Drop PDF here" : state === "validating" ? "Validating document…" : state === "uploading" ? "Uploading report…" : state === "processing" ? "Report uploaded" : state === "invalid" || state === "failed" ? "Choose another document" : "Drop PDF here"}</h2><p>{state === "processing" ? "Reading document and preparing structured extraction…" : state === "invalid" || state === "failed" ? error : "or"}</p>{!busy && state !== "invalid" && state !== "failed" && <button className="primary-action" type="button" onClick={browse}>Browse files</button>}{(state === "invalid" || state === "failed") && <button className="secondary-action retry-action" type="button" onClick={reset}><RefreshCw size={14} /> Try Again</button>}<div className="upload-meta"><span>PDF files only</span><span>Maximum 10 MB</span><span>Synthetic data only</span></div></div><div className="upload-note"><ShieldCheck size={15} /><span>Files are validated and processed by the MedLens backend. The original filename is retained as metadata only.</span></div></>}<Link className="back-link" to={`/patients/${patientId}/reports`}>Back to patient reports</Link></div>;
}

function ReadyState({ report, file, onAnother, onReview }: { report: ReportUpload; file: File; onAnother: () => void; onReview: () => void }) { return <section className="ready-panel" role="status"><div className="ready-heading"><span className="ready-icon"><CheckCircle2 size={24} /></span><div><div className="eyebrow">Upload complete</div><h2>Report ready for review</h2><p>The document has been accepted by the backend. Extraction review remains a separate step.</p></div></div><dl className="report-details"><div><dt>Original filename</dt><dd>{file.name}</dd></div><div><dt>File type</dt><dd>PDF document</dd></div><div><dt>Size</dt><dd>{(file.size / 1024 / 1024).toFixed(2)} MB</dd></div><div><dt>Pages</dt><dd>{report.pages || "Not reported"}</dd></div><div><dt>Report ID</dt><dd>#{report.id}</dd></div><div><dt>Processing state</dt><dd>{report.processing_status}</dd></div></dl><div className="ready-actions"><button className="primary-action" type="button" onClick={onReview}>Review Extraction <ArrowRight size={16} /></button><button className="secondary-action retry-action" type="button" onClick={onAnother}>Upload Another Report</button></div></section>; }
